"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import AppShell from "./AppShell";
import { api, API, MEDIA_ORIGIN, token } from "@/lib/api";
import { Empty, Evidence, Loading, ProgressBar, RiskMeter, Status } from "./UI";

type Row=Record<string,unknown>;
type Mode="digital-twin"|"schedule"|"captures"|"progress"|"changes"|"safety"|"quality"|"risk"|"reports"|"cameras"|"alerts"|"audit";
const config:Record<Mode,{title:string;subtitle:string;path:string}>={
 "digital-twin":{title:"Digital Twin",subtitle:"IFC hierarchy, element state, linked construction context, and verification confidence.",path:"/bim/models?project_id=1"},
 schedule:{title:"4D Schedule",subtitle:"Planned and approved progress, dependencies, criticality, contractors, and risk.",path:"/schedule/activities?project_id=1"},
 captures:{title:"Site Captures",subtitle:"Persisted image and MP4 evidence with camera, zone, and synthetic-source disclosure.",path:"/captures?project_id=1"},
 progress:{title:"Progress Review",subtitle:"Human governance for AI-estimated construction progress without destructive overwrites.",path:"/progress/observations?project_id=1"},
 changes:{title:"Change Analysis",subtitle:"Aligned before-and-after comparison, change mask area, confidence, and reviewer status.",path:"/changes?project_id=1"},
 safety:{title:"Safety Operations",subtitle:"Deduplicated rule events with track evidence, zone context, assignment, and resolution state.",path:"/safety/events?project_id=1"},
 quality:{title:"Quality Intelligence",subtitle:"Candidate-only visual observations, corrective actions, due dates, and reviewer outcomes.",path:"/quality/observations?project_id=1"},
 risk:{title:"Risk Forecast",subtitle:"Transparent delay-risk contributions rather than unexplained black-box scores.",path:"/risk/activities?project_id=1"},
 reports:{title:"Reports",subtitle:"Project-data-backed PDF reports with KPIs, risks, alerts, and generation parameters.",path:"/reports?project_id=1"},
 cameras:{title:"Camera Health",subtitle:"Source status, last heartbeat, work-zone context, and diagnostic errors.",path:"/cameras?project_id=1"},
 alerts:{title:"Alerts",subtitle:"Actionable construction exceptions with severity, source entity, and acknowledgement state.",path:"/alerts?project_id=1"},
 audit:{title:"Audit Log",subtitle:"Traceable actor actions, before/after values, entity references, and correlation IDs.",path:"/audit?project_id=1"}
};
const str=(r:Row,k:string)=>String(r[k]??""); const num=(r:Row,k:string)=>Number(r[k]??0); const arr=(r:Row,k:string)=>Array.isArray(r[k])?r[k] as Row[]:[];

export default function Operations({mode}:{mode:Mode}){const c=config[mode];const [rows,setRows]=useState<Row[]>([]);const [elements,setElements]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const result=await api<Row[]>(c.path);setRows(result);if(mode==="digital-twin"&&result[0]){const completed=result.find(x=>str(x,"status")==="completed")??result[0];setElements(await api<Row[]>(`/bim/models/${num(completed,"id")}/elements`));}}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setLoading(false)}},[c.path,mode]);useEffect(()=>{load()},[load]);
 async function review(id:number,decision:string,approved?:number){try{await api(`/progress/observations/${id}/review`,{method:"POST",body:JSON.stringify({decision,approved_progress:approved,notes:"Reviewed from BuildTwin operations console"})});setNotice(`Observation ${decision}. Effective project progress recalculated.`);load()}catch(e){setError(e instanceof Error?e.message:"Review failed")}}
 async function acknowledge(id:number){try{await api(`/alerts/${id}/acknowledge`,{method:"POST"});setNotice("Alert acknowledged and audit event recorded.");load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}}
 async function generateReport(){try{const x=await api<{id:number;download_url:string}>("/reports/generate?project_id=1",{method:"POST"});setNotice(`Report ${x.id} generated from current persisted data.`);load()}catch(e){setError(e instanceof Error?e.message:"Generation failed")}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);data.set("project_id","1");const kind=String(data.get("kind"));data.delete("kind");try{const response=await fetch(`${API}/captures/${kind}`,{method:"POST",headers:{Authorization:`Bearer ${token()}`},body:data});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Upload failed");setNotice(`${kind} capture uploaded and persisted.`);form.reset();load()}catch(e){setError(e instanceof Error?e.message:"Upload failed")}}
 return <AppShell title={c.title} subtitle={c.subtitle}>{error&&<div className="error-box">{error}</div>}{notice&&<div className="success-box">{notice}</div>}{mode==="captures"&&<form className="upload-bar" onSubmit={upload}><select name="kind"><option value="images">Image</option><option value="videos">MP4 video</option></select><input name="zone_id" defaultValue="1" aria-label="Zone ID"/><input type="file" name="file" required/><button className="button primary">Upload capture</button></form>}{mode==="reports"&&<button className="button primary action-top" onClick={generateReport}>Generate current PDF</button>}{loading?<Loading/>:render(mode,rows,elements,{review,acknowledge})}</AppShell>}

type Actions={review:(id:number,decision:string,approved?:number)=>void;acknowledge:(id:number)=>void};
function render(mode:Mode,rows:Row[],elements:Row[],actions:Actions){if(mode==="digital-twin")return <><section className="kpi-grid compact">{rows.map(r=><article className="kpi" key={num(r,"id")}><span>{str(r,"filename")}</span><strong>{num(r,"element_count")}</strong><small>elements · {num(r,"failure_count")} parse failures</small><Status value={str(r,"status")}/></article>)}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">IFC ELEMENT REGISTER</span><h2>Hierarchical twin explorer</h2></div><span className="count-badge">{elements.length}</span></div><div className="card-table">{elements.map(e=><article key={num(e,"id")}><div className="element-icon">{str(e,"element_type").replace("Ifc","").slice(0,2).toUpperCase()}</div><section><b>{str(e,"name")}</b><small>{str(e,"ifc_guid")}</small><div className="tags"><Status value={str(e,"element_type")}/><Status value={str(e,"progress_status")}/><span>{str(e,"floor_name")||"Unassigned floor"}</span><span>{str(e,"material")||"Material pending"}</span></div></section><div className="element-progress"><strong>{num(e,"progress_percent")}%</strong><ProgressBar value={num(e,"progress_percent")}/><small>{Math.round(num(e,"confidence")*100)}% confidence</small></div></article>)}</div></section></>;
 if(mode==="schedule")return <section className="panel"><div className="panel-head"><div><span className="eyebrow">MASTER PROGRAM</span><h2>Activity timeline and variance</h2></div><span className="count-badge">{rows.length}</span></div><div className="schedule-list">{rows.map(r=><article key={num(r,"id")}><header><span><b>{str(r,"external_id")}</b><strong>{str(r,"name")}</strong></span><Status value={str(r,"status")}/></header><div className="schedule-meta"><span>{str(r,"planned_start")} → {str(r,"planned_finish")}</span><span>{str(r,"contractor")}</span>{Boolean(r.critical)&&<Status value="critical path"/>}</div><ProgressBar value={num(r,"approved_progress")} planned={num(r,"planned_progress")}/><footer><span>Approved <b>{num(r,"approved_progress")}%</b></span><span>AI <b>{num(r,"ai_progress")}%</b></span><span>Plan <b>{num(r,"planned_progress")}%</b></span><span>Risk <b>{num(r,"risk_score")}</b></span></footer></article>)}</div></section>;
 if(mode==="captures")return rows.length?<div className="gallery">{rows.map(r=><article key={num(r,"id")}><div className="capture-preview">{str(r,"kind")==="image"?<Evidence src={str(r,"url")} alt={str(r,"filename")}/>:<div className="video-card"><span>▶</span><b>MP4 evidence</b></div>}</div><header><b>{str(r,"filename")}</b><Status value={str(r,"kind")}/></header><p>Zone {str(r,"zone_id")} · Camera {str(r,"camera_id")||"unassigned"}</p><small>{str(r,"captured_at")} {Boolean(r.synthetic)&&"· synthetic demo asset"}</small></article>)}</div>:<Empty text="Upload a site image or MP4 capture."/>;
 if(mode==="progress")return <div className="review-grid">{rows.map(r=><article className="review-card" key={num(r,"id")}><Evidence src={str(r,"evidence_url")} alt="Progress evidence"/><div className="review-body"><div className="panel-head"><div><small>{str(r,"external_id")}</small><h2>{str(r,"activity")}</h2></div><Status value={str(r,"review_status")}/></div><div className="review-metrics"><span><small>Previous</small><b>{num(r,"previous_progress")}%</b></span><span><small>AI estimate</small><b>{num(r,"estimated_progress")}%</b></span><span><small>Confidence</small><b>{Math.round(num(r,"confidence")*100)}%</b></span></div><p>{str(r,"algorithm")} · v{str(r,"algorithm_version")}</p><p>{str(r,"review_notes")}</p>{str(r,"review_status")==="pending"&&<div className="review-actions"><button className="button primary" onClick={()=>actions.review(num(r,"id"),"approved",num(r,"estimated_progress"))}>Approve estimate</button><button className="button danger" onClick={()=>actions.review(num(r,"id"),"rejected")}>Reject</button></div>}</div></article>)}</div>;
 if(mode==="changes")return <div className="review-grid">{rows.map(r=><article className="review-card" key={num(r,"id")}><Evidence src={str(r,"overlay_url")} alt="Change overlay"/><div className="review-body"><div className="panel-head"><div><small>ZONE {str(r,"zone_id")}</small><h2>{num(r,"changed_area_percent").toFixed(2)}% changed area</h2></div><Status value={str(r,"review_status")}/></div><div className="review-metrics"><span><small>Alignment</small><b>{str(r,"alignment_status")}</b></span><span><small>Confidence</small><b>{Math.round(num(r,"confidence")*100)}%</b></span><span><small>Baseline</small><b>#{str(r,"baseline_asset_id")}</b></span></div><p>{str(r,"reviewer_notes")||"Awaiting reviewer interpretation."}</p></div></article>)}</div>;
 if(mode==="safety")return <div className="event-grid">{rows.map(r=><article key={num(r,"id")}><Evidence src={str(r,"evidence_url")} alt="Safety evidence"/><section><div className="panel-head"><Status value={str(r,"severity")}/><Status value={str(r,"status")}/></div><h2>{str(r,"event_type").replaceAll("_"," ")}</h2><p>{str(r,"notes")}</p><div className="event-meta"><span>Confidence <b>{Math.round(num(r,"confidence")*100)}%</b></span><span>Zone <b>#{str(r,"zone_id")}</b></span><span>Camera <b>#{str(r,"camera_id")}</b></span><span>Tracks <b>{arr(r,"detection_boxes").length}</b></span></div></section></article>)}</div>;
 if(mode==="quality")return <section className="panel"><div className="card-table">{rows.map(r=><article key={num(r,"id")}><Evidence src={str(r,"evidence_url")} alt="Quality candidate"/><section><b>{str(r,"candidate_type").replaceAll("_"," ")}</b><div className="tags"><Status value={str(r,"severity")}/><Status value={str(r,"status")}/><span>{Math.round(num(r,"confidence")*100)}% confidence</span></div><p>{str(r,"corrective_action")||str(r,"reviewer_notes")}</p><small>{str(r,"due_date")?`Due ${str(r,"due_date")}`:"No open corrective due date"}</small></section></article>)}</div></section>;
 if(mode==="risk")return <div className="risk-list">{rows.map(r=><article key={num(r,"id")}><RiskMeter score={num(r,"score")}/><section><header><div><small>{str(r,"external_id")}</small><h2>{str(r,"activity")}</h2></div><Status value={str(r,"band")}/></header><ProgressBar value={num(r,"approved_progress")} planned={num(r,"planned_progress")}/><div className="factor-list">{arr(r,"factors").map((f,i)=><div key={i}><span>{str(f,"name").replaceAll("_"," ")}</span><p>{str(f,"reason")}</p><b>+{num(f,"contribution")}</b></div>)}</div><footer>{str(r,"recommendation")} <small>Model {str(r,"model_version")}</small></footer></section></article>)}</div>;
 if(mode==="reports")return <section className="panel"><div className="card-table">{rows.map(r=><article key={num(r,"id")}><div className="element-icon">PDF</div><section><b>{str(r,"report_type").replaceAll("_"," ")}</b><small>Generated {str(r,"generated_at")}</small></section><a className="button ghost" href={`${MEDIA_ORIGIN}${str(r,"download_url")}`} onClick={e=>{e.preventDefault();fetch(`${MEDIA_ORIGIN}${str(r,"download_url")}`,{headers:{Authorization:`Bearer ${token()}`}}).then(x=>x.blob()).then(blob=>{const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=`buildtwin-report-${num(r,"id")}.pdf`;a.click();URL.revokeObjectURL(u)})}}>Download PDF</a></article>)}</div></section>;
 if(mode==="cameras")return <div className="camera-grid">{rows.map(r=><article key={num(r,"id")}><div className={`camera-lens ${str(r,"status")}`}>◉</div><section><header><b>{str(r,"name")}</b><Status value={str(r,"status")}/></header><p>{str(r,"source_type")} source · Zone #{str(r,"zone_id")}</p><small>Last seen {str(r,"last_seen_at")}</small>{str(r,"last_error")&&<div className="error-inline">{str(r,"last_error")}</div>}</section></article>)}</div>;
 if(mode==="alerts")return <div className="alert-list">{rows.map(r=><article key={num(r,"id")}><Status value={str(r,"severity")}/><section><header><b>{str(r,"title")}</b><Status value={str(r,"status")}/></header><p>{str(r,"message")}</p><small>{str(r,"entity_type")} #{str(r,"entity_id")} · {str(r,"created_at")}</small></section>{str(r,"status")==="unread"&&<button className="button ghost" onClick={()=>actions.acknowledge(num(r,"id"))}>Acknowledge</button>}</article>)}</div>;
 return <section className="panel"><div className="audit-table"><div className="audit-row head"><span>Actor</span><span>Action</span><span>Entity</span><span>Change</span><span>Correlation</span><span>Time</span></div>{rows.map(r=><div className="audit-row" key={num(r,"id")}><span>{str(r,"actor")}</span><span><b>{str(r,"action")}</b></span><span>{str(r,"entity_type")} #{str(r,"entity_id")}</span><span><code>{JSON.stringify(r.after_values)}</code></span><span><code>{str(r,"correlation_id")||"—"}</code></span><span>{str(r,"created_at")}</span></div>)}</div></section>;
}
